# Generated by Django 4.2.7 on 2023-11-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.IntegerField()),
                ('articleName', models.CharField(max_length=150)),
                ('articleContent', models.CharField(max_length=3000000)),
                ('likes', models.IntegerField()),
                ('dislikes', models.IntegerField()),
                ('author', models.CharField(max_length=150)),
            ],
        ),
    ]
