# Generated by Django 4.2.7 on 2023-11-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('histolog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='_id',
        ),
        migrations.AlterField(
            model_name='article',
            name='articleContent',
            field=models.TextField(),
        ),
    ]
